services:

  django:
    container_name: tr-backend
    build:
      context: ./
      dockerfile: django.dockerfile
    depends_on:
      database:
        condition: service_started
        restart: true
      redis:
        condition: service_started
        restart: true
    entrypoint: django-entrypoint.sh
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: dump-ubuntu-barcelona
      SECRET_KEY: random-key-123456
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: tr-database
      DB_USER: tr-user
      DB_PASSWORD: tr-password
      DB_HOST: database
      DB_PORT: 5432
      DOMAIN: dump-ubuntu-barcelona
      DOMAIN_URL: http://dump-ubuntu-barcelona
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEFAULT_FROM_EMAIL: no-reply@dump-ubuntu-barcelona
      STATIC_URL: /static/
      STATIC_ROOT: static
      MEDIA_URL: /media/
      EMAIL_HOST: mailhog
      EMAIL_USE_TLS: "False"
      EMAIL_USE_SSL: "False"
      EMAIL_PORT: 1025
      EMAIL_USER: tr-mail@tr.mail
      EMAIL_PASSWORD: tr-password
    expose:
      - 8000
    volumes:
      - ./:/usr/app/
    working_dir: /usr/app/

  database:
    container_name: tr-database
    image: postgres:16.4-alpine3.20

  redis:
    container_name: tr-redis
    image: redis:7.4-alpine
    depends_on:
      database:
        condition: services_started
        restart: true

  server:
    container_name: tr-server
    image: caddy:2.8-alpine
    depends_on:
      django:
        condition: service_started
        restart: true
