name: ft_transcendece

services:
  database:
    container_name: tr-database
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - tr-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME?err}
      - POSTGRES_USER=${DB_USER?err}
      - POSTGRES_PASSWORD=${DB_PASSWORD?err}
      - PGDATA=/var/lib/postgresql/data/pgdata
    attach: false
    restart: on-failure:3

volumes:
  db:
    name: tr-data
    driver: local
    driver_opts:
      type: none
      o: bind
      # path relative to the file docker-compose.yml's directory
      device: "./database/data"

networks:
  tr-network:
    name: "transcendence-network"

