name: transcendece

services:
  database:
    container_name: postgresql
    image: postgres:16.3-alpine3.20
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - transcendence-network
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: unless-stopped

networks:
  transcendence-network:
    name: "transcendence-network"

